deployment:
  name: mock-sris
  containers:
    name: mock-sris-backend
    image: 463471358064.dkr.ecr.eu-central-1.amazonaws.com/app/usct/dev-backend:0.0.11
    imagePullPolicy: "Always"

service:
  name: backend
  port: 8080

oidcKeystorePassword: ""
