deployment:
  name: backend
  containers:
    name: dev-backend
    image: 463471358064.dkr.ecr.eu-central-1.amazonaws.com/app/usct/dev-backend:0.0.10
    imagePullPolicy: IfNotPresent

service:
  name: backend
  port: 8080