deployment:
  name: usct-backend
  containers:
    name: usct-backend
    image: 161826879607.dkr.ecr.eu-central-1.amazonaws.com/app/usct/backend:latest
    imagePullPolicy: "Always"

service:
  name: backend
  port: 8080
  logLevel: "INFO"
  authmode: local

oidcKeystorePassword: ""

payment:
  config:
    mode: "emulator"
  variables:
    source_bb_id: "USCT-BB"
    government_identifier: "066283"
  bb:
    im:
      base_url: "http://sandbox-xroad-ss2.im-xroad.svc.cluster.local:8080/r1/SANDBOX/GOV/PROVIDER/PAYMENT/emulator"
      header: "SANDBOX/ORG/CLIENT/TEST"

paymenthub:
  bb:
    account_mapper_url: "http://sandbox-xroad-ss2.im-xroad.svc.cluster.local:8080/r1/SANDBOX/GOV/PROVIDER/PAYMENT/account-mapper"
    bulk_connector_url: "http://sandbox-xroad-ss2.im-xroad.svc.cluster.local:8080/r1/SANDBOX/GOV/PROVIDER/PAYMENT/bulk-connector"
    callback_base_url: "http://backend.usct.svc.cluster.local:8080"
    registering_institution_id: 123456
    tenant: rhino
    program_id: "00"
    jws_tenant_private_key: ""
    payment_mode: "mojaloop"
    im:
      header: "SANDBOX/ORG/CLIENT/TEST"

callback:
  cidr: "0.0.0.0/0,::/0"

openImis:
  url: "http://sandbox-xroad-ss2.im-xroad.svc.cluster.local:8080/r1/SANDBOX/GOV/PROVIDER/DIGITAL-REGISTRIES/api/data/registryname/111?search=package&filter=phone"
  emulator_url: "http://sandbox-xroad-ss2.im-xroad.svc.cluster.local:8080/r1/SANDBOX/GOV/PROVIDER/DIGITAL-REGISTRIES/emulator/api/v1/data/bpkg/1.0"
  user: "admin"
  password: "govstack"
  mode: "open-imis"
  header: "SANDBOX/ORG/CLIENT/TEST"

igrant:
  url: "http://sandbox-xroad-ss2.im-xroad.svc.cluster.local:8080/r1/SANDBOX/GOV/PROVIDER/CONSENT/api/v2/service/individual/record/"
  token: ""
  dataAgreementId: ""
  header: "SANDBOX/ORG/CLIENT/TEST"
  mode: "igrant"
